//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Updater.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Updater.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates....
        /// </summary>
        public static string Checkingforupdates {
            get {
                return ResourceManager.GetString("Checkingforupdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete..
        /// </summary>
        public static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading version info....
        /// </summary>
        public static string Downloadingversioninfo {
            get {
                return ResourceManager.GetString("Downloadingversioninfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File could not be downloaded..
        /// </summary>
        public static string Filecouldnotbedownloaded {
            get {
                return ResourceManager.GetString("Filecouldnotbedownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new updates available..
        /// </summary>
        public static string Nonewupdates {
            get {
                return ResourceManager.GetString("Nonewupdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find UOMachine folder, please select the folder containing UOMachine..
        /// </summary>
        public static string Unablefindfolder {
            get {
                return ResourceManager.GetString("Unablefindfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOMachine running.
        /// </summary>
        public static string UOMachineRunning {
            get {
                return ResourceManager.GetString("UOMachineRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update is available, please close UOMachine to update..
        /// </summary>
        public static string UOMachineRunningPleaseClose {
            get {
                return ResourceManager.GetString("UOMachineRunningPleaseClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOMachine Updater.
        /// </summary>
        public static string UOMachineUpdater {
            get {
                return ResourceManager.GetString("UOMachineUpdater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting....
        /// </summary>
        public static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
    }
}
