//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UOMachine.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UOMachine.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About....
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add assembly reference.
        /// </summary>
        public static string Addassemblyreference {
            get {
                return ResourceManager.GetString("Addassemblyreference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always light patch.
        /// </summary>
        public static string Alwayslightpatch {
            get {
                return ResourceManager.GetString("Alwayslightpatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Documentation.
        /// </summary>
        public static string APIDoc {
            get {
                return ResourceManager.GetString("APIDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attached to client.
        /// </summary>
        public static string Attachedtoclient {
            get {
                return ResourceManager.GetString("Attachedtoclient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find Razor.exe/Crypt.dll.
        /// </summary>
        public static string CannotfindRazor {
            get {
                return ResourceManager.GetString("CannotfindRazor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates....
        /// </summary>
        public static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client exited..
        /// </summary>
        public static string Clientexited {
            get {
                return ResourceManager.GetString("Clientexited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client started.
        /// </summary>
        public static string Clientstarted {
            get {
                return ResourceManager.GetString("Clientstarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing.
        /// </summary>
        public static string Closing {
            get {
                return ResourceManager.GetString("Closing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiler error.
        /// </summary>
        public static string Compilererror {
            get {
                return ResourceManager.GetString("Compilererror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert tabs to spaces.
        /// </summary>
        public static string Converttabstospaces {
            get {
                return ResourceManager.GetString("Converttabstospaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut / Copy whole line.
        /// </summary>
        public static string CutCopywholeline {
            get {
                return ResourceManager.GetString("CutCopywholeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error attaching to Razor client..
        /// </summary>
        public static string ErrorattachingtoRazorclient {
            get {
                return ResourceManager.GetString("ErrorattachingtoRazorclient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error initializing UO Machine, please try again..
        /// </summary>
        public static string Errorinitializing {
            get {
                return ResourceManager.GetString("Errorinitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error injecting dll into target process.
        /// </summary>
        public static string Errorinjectingdll {
            get {
                return ResourceManager.GetString("Errorinjectingdll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening file, make sure it&apos;s not in use..
        /// </summary>
        public static string Erroropeningfile {
            get {
                return ResourceManager.GetString("Erroropeningfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error patching client encryption!.
        /// </summary>
        public static string Errorpatchingclientencryption {
            get {
                return ResourceManager.GetString("Errorpatchingclientencryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error patching stamina check!.
        /// </summary>
        public static string Errorpatchingstaminacheck {
            get {
                return ResourceManager.GetString("Errorpatchingstaminacheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error resolving hostname.
        /// </summary>
        public static string Errorresolvinghostname {
            get {
                return ResourceManager.GetString("Errorresolvinghostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving file, please choose another location..
        /// </summary>
        public static string Errorsavingfile {
            get {
                return ResourceManager.GetString("Errorsavingfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error setting game window size!.
        /// </summary>
        public static string Errorsettinggamewindowsize {
            get {
                return ResourceManager.GetString("Errorsettinggamewindowsize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error starting client.
        /// </summary>
        public static string Errorstartingclient {
            get {
                return ResourceManager.GetString("Errorstartingclient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error with always light patch!.
        /// </summary>
        public static string Errorwithalwayslightpatch {
            get {
                return ResourceManager.GetString("Errorwithalwayslightpatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error with GAC installation, please see log for details..
        /// </summary>
        public static string ErrorwithGACinstallation {
            get {
                return ResourceManager.GetString("ErrorwithGACinstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception caught, please check log..
        /// </summary>
        public static string Exceptioncaught {
            get {
                return ResourceManager.GetString("Exceptioncaught", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force game size.
        /// </summary>
        public static string Forcegamesize {
            get {
                return ResourceManager.GetString("Forcegamesize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format document.
        /// </summary>
        public static string Formatdocument {
            get {
                return ResourceManager.GetString("Formatdocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full caching (about 70 MB).
        /// </summary>
        public static string Fullcaching {
            get {
                return ResourceManager.GetString("Fullcaching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indentation size:.
        /// </summary>
        public static string Indentationsize {
            get {
                return ResourceManager.GetString("Indentationsize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for port, please fix..
        /// </summary>
        public static string Invalidvalueforport {
            get {
                return ResourceManager.GetString("Invalidvalueforport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value(s) present in options.xml, please fix..
        /// </summary>
        public static string Invalidvaluepresentinoptions {
            get {
                return ResourceManager.GetString("Invalidvaluepresentinoptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launching client.
        /// </summary>
        public static string Launchingclient {
            get {
                return ResourceManager.GetString("Launchingclient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory allocation failed..
        /// </summary>
        public static string Memoryallocationfailed {
            get {
                return ResourceManager.GetString("Memoryallocationfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiUO patch failed!.
        /// </summary>
        public static string MultiUOpatchfailed {
            get {
                return ResourceManager.GetString("MultiUOpatchfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None (0 extra).
        /// </summary>
        public static string None0extra {
            get {
                return ResourceManager.GetString("None0extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch client encryption.
        /// </summary>
        public static string Patchclientencryption {
            get {
                return ResourceManager.GetString("Patchclientencryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch encryption.
        /// </summary>
        public static string Patchencryption {
            get {
                return ResourceManager.GetString("Patchencryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patching client.
        /// </summary>
        public static string Patchingclient {
            get {
                return ResourceManager.GetString("Patchingclient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch Felucca stamina check (&lt; 7.0.0.0).
        /// </summary>
        public static string Patchstamcheck {
            get {
                return ResourceManager.GetString("Patchstamcheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        public static string Performance {
            get {
                return ResourceManager.GetString("Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process creation failed..
        /// </summary>
        public static string Processcreationfailed {
            get {
                return ResourceManager.GetString("Processcreationfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razor.
        /// </summary>
        public static string Razor {
            get {
                return ResourceManager.GetString("Razor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razor installation folder:.
        /// </summary>
        public static string Razorinstallationfolder {
            get {
                return ResourceManager.GetString("Razorinstallationfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razor successfully launched.
        /// </summary>
        public static string Razorsuccessfullylaunched {
            get {
                return ResourceManager.GetString("Razorsuccessfullylaunched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResumeThread failed..
        /// </summary>
        public static string ResumeThreadfailed {
            get {
                return ResourceManager.GetString("ResumeThreadfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script running.
        /// </summary>
        public static string Scriptrunning {
            get {
                return ResourceManager.GetString("Scriptrunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script stopped.
        /// </summary>
        public static string Scriptstopped {
            get {
                return ResourceManager.GetString("Scriptstopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script stopping.
        /// </summary>
        public static string Scriptstopping {
            get {
                return ResourceManager.GetString("Scriptstopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select assembles to reference.
        /// </summary>
        public static string Selectassembliestoreference {
            get {
                return ResourceManager.GetString("Selectassembliestoreference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server:.
        /// </summary>
        public static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server uses OSI encryption.
        /// </summary>
        public static string ServerusesOSIencryption {
            get {
                return ResourceManager.GetString("ServerusesOSIencryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show box for control characters.
        /// </summary>
        public static string Showboxforcontrolcharacters {
            get {
                return ResourceManager.GetString("Showboxforcontrolcharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show spaces.
        /// </summary>
        public static string Showspaces {
            get {
                return ResourceManager.GetString("Showspaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show tabs.
        /// </summary>
        public static string Showtabs {
            get {
                return ResourceManager.GetString("Showtabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start new client.
        /// </summary>
        public static string Startnewclient {
            get {
                return ResourceManager.GetString("Startnewclient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start new Razor instance.
        /// </summary>
        public static string StartnewRazorinstance {
            get {
                return ResourceManager.GetString("StartnewRazorinstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start new UOSteam instance.
        /// </summary>
        public static string StartnewUOSteaminstance {
            get {
                return ResourceManager.GetString("StartnewUOSteaminstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start script.
        /// </summary>
        public static string Startscript {
            get {
                return ResourceManager.GetString("Startscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static indices only (about 20 MB).
        /// </summary>
        public static string Staticindicesonly {
            get {
                return ResourceManager.GetString("Staticindicesonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statics caching (memory required).
        /// </summary>
        public static string Staticscaching {
            get {
                return ResourceManager.GetString("Staticscaching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status : Ready.
        /// </summary>
        public static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping script.
        /// </summary>
        public static string Stoppingscript {
            get {
                return ResourceManager.GetString("Stoppingscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop script.
        /// </summary>
        public static string Stopscript {
            get {
                return ResourceManager.GetString("Stopscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        public static string Unknownerror {
            get {
                return ResourceManager.GetString("Unknownerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UO client path:.
        /// </summary>
        public static string UOclientpath {
            get {
                return ResourceManager.GetString("UOclientpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UO installation folder:.
        /// </summary>
        public static string UOinstallationfolder {
            get {
                return ResourceManager.GetString("UOinstallationfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOSteam.
        /// </summary>
        public static string UOSteam {
            get {
                return ResourceManager.GetString("UOSteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOSteam executable path:.
        /// </summary>
        public static string UOSteamexecutablepath {
            get {
                return ResourceManager.GetString("UOSteamexecutablepath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOSteam installation folder:.
        /// </summary>
        public static string UOSteaminstallationfolder {
            get {
                return ResourceManager.GetString("UOSteaminstallationfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOSteam launch failed..
        /// </summary>
        public static string UOSteamlaunchfailed {
            get {
                return ResourceManager.GetString("UOSteamlaunchfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter valid options to start UO Machine..
        /// </summary>
        public static string Youmustentervalidoptions {
            get {
                return ResourceManager.GetString("Youmustentervalidoptions", resourceCulture);
            }
        }
    }
}
